name: Lint and Test

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: |
          poetry install

      - name: Find changed Python files
        id: find_changed_files
        run: |
          BASE_BRANCH=$(echo "${{ github.base_ref }}")
          git fetch origin $BASE_BRANCH
          COMMON_ANCESTOR=$(git merge-base HEAD origin/$BASE_BRANCH)
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB $COMMON_ANCESTOR)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run flake8 on changed files
        run: |
          for file in $CHANGED_FILES; do
            if [[ $file == *.py ]]; then
              poetry run flake8 $file
            fi
          done
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: |
          poetry install

      - name: Set environment variable
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Test with pytest
        run: |
          poetry run pytest tests
