name: CI

on: pull_request

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.python-version.outputs.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        id: python-version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: |
          poetry install

      - name: Set environment variable
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Lint with flake8
        run: |
          poetry run flake8 .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2

      - name: Test with pytest
        run: |
          poetry run pytest tests
